// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBannerlink: typeof import('./src/components/base-bannerlink.vue')['default']
    BaseCarousel: typeof import('./src/components/base-carousel.vue')['default']
    BaseHeader: typeof import('./src/components/base-header.vue')['default']
    BaseModel: typeof import('./src/components/base-model.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfButton: typeof import('./src/components/self-button.vue')['default']
    SelfTabs: typeof import('./src/components/self-tabs.vue')['default']
  }
}

export {}
