// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBannerlink: typeof import('./src/components/base-bannerlink.vue')['default']
    BaseCarousel: typeof import('./src/components/base-carousel.vue')['default']
    BaseHeader: typeof import('./src/components/base-header.vue')['default']
    BaseModal: typeof import('./src/components/base-modal.vue')['default']
    NImage: typeof import('naive-ui')['NImage']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfButton: typeof import('./src/components/self-button.vue')['default']
    SelfSvgicon: typeof import('./src/components/self-svgicon.vue')['default']
    SelfTabs: typeof import('./src/components/self-tabs.vue')['default']
  }
}

export {}
